version: '3.4'

services:
  shoppingsmart.services.itemscatalog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PW=Passw0rd
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    volumes:
      - type: volume
        source: mssql-server-icol
        target: /var/opt/mssql

    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
volumes:
  mssql-server-icol: 