# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# To put this Action back to trigger builds and deployments when new commits please select the barnch.

name: Build and deploy ASP.Net Core app to Azure Web App - ShoppingSmart

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - run: echo "env.DOTNET_ROOT = ${{env.DOTNET_ROOT}}"

      - name: Build with dotnet
        run: dotnet build ShoppingSmart.Services.ItemsCatalog.csproj --configuration Release
        
      - run: echo "env.DOTNET_ROOT = ${{env.DOTNET_ROOT}}/myapp/ShoppingSmart.Services.ItemsCatalog.csproj"

      - name: dotnet publish
        run: dotnet publish ShoppingSmart.Services.ItemsCatalog.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ShoppingSmart'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_19621A8258604A4593D5997A7B61907B }}
          package: .
